# Generated by Django 3.1.1 on 2020-09-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_text',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview_text',
            field=models.CharField(max_length=200, verbose_name='Preview Text'),
        ),
    ]
