# Generated by Django 3.1.1 on 2020-09-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_App', '0002_auto_20200912_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
